<a href="https://colab.research.google.com/github/akhil27/Akhil_INFO5731_SPRING2025/blob/main/Indraganti_Akhil_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment - 1**

This assignment includes range of programming tasks and data analysis exercises, aiming to enhance your Python skills and proficiency in string manipulation, numerical computations, and data science. Follow the instructions carefully and design well-structured Python programs to address each question.


1.  Question 1-5 using AI assistance is strictly prohibted
2.  Question 6-7 AI assitance is recommended by following guidelines.

Guidelines and expectations file can be found in week 2 module.

Late Submission will have a penalty of 10% reduction for each day after the deadline.

# Question 1 (10 points).

The formula that describes the volume V of a hemisphere with radius r is the following:

$ V=\frac{2}{3}\ast\ \pi\ast\ r^3 $

Write a program to calculate the value of V when r is in the range of even numbers from 1-20. Output the result in the following format:

	r	V
	2	…
	4	…
	6	…
	.
	.
	.
	20	…


In [ ]:
#Question 1: Volume of Hemisphere
import math
r=print("\tr\tv")
for r in range(2,22,2):
  v=(2/3)*math.pi*r**3
  print(f"\t{r}\t{v:.3f}")
  r+=2



	r	v
	2	16.755
	4	134.041
	6	452.389
	8	1072.330
	10	2094.395
	12	3619.115
	14	5747.020
	16	8578.642
	18	12214.512
	20	16755.161


# Question 2 (10 points)

(a) Write a Python program to generate a sequence of 12 random numbers falling within the range of 50 to 150.

(b) Arrange the generated numbers in ascending order. Display the sorted list.

(c) Extend the program to arrange the numbers in descending order as well. Present the sorted list accordingly.

(d) Compute and output the average of the entire group of generated numbers.

(e) Enhance the program to calculate and display the average of the first 6 numbers from both the ascending and descending sorted lists.

In [ ]:
#Question 2
import numpy as np
import random
random_numbers=[]
for i in range(12):
  random_numbers.append(random.randint(15,50))
  #a
print("Unsorted list of 12 random numbers between 15 and 50: ",random_numbers)

#b
random_numbers.sort()
print("A list of 12 random numbers between 15 and 50 in ascending order:", random_numbers)

#c
random_numbers.sort(reverse=True)
print("A list of 12 random numbers between 15 and 50 in descending order:", random_numbers)

#d
avg=sum(random_numbers)/len(random_numbers)
print("The average of the numbers in the list is:", avg)

#e
print("The smallest six numbers in the list are: ", end="")
random_numbers.sort()
for i in random_numbers[:6]:
  print(i,end="\t")
print()
print(np.average(random_numbers[:6]))

print("The largest six numbers in the list are: ", end="")
random_numbers.sort(reverse=True)
for i in random_numbers[:6]:
  print(i,end="\t")
print()
print(np.average(random_numbers[:6]))






Unsorted list of 12 random numbers between 15 and 50:  [30, 18, 16, 28, 24, 18, 43, 50, 42, 44, 23, 23]
A list of 12 random numbers between 15 and 50 in ascending order: [16, 18, 18, 23, 23, 24, 28, 30, 42, 43, 44, 50]
A list of 12 random numbers between 15 and 50 in descending order: [50, 44, 43, 42, 30, 28, 24, 23, 23, 18, 18, 16]
The average of the numbers in the list is: 29.916666666666668
The smallest six numbers in the list are: 16	18	18	23	23	24	
20.333333333333332
The largest six numbers in the list are: 50	44	43	42	30	28	
39.5


# Question 3 (10 points).

Create a Python program that encompasses various string manipulation task:

(a) Prompt the user to input two sentences.

(b) Transform each sentence into a list, where each element corresponds to a word in the sentence. For example, if the sentences are "Hello, how are you doing today?" and "This is an example sentence for the program!"

The program should output:
['Hello', ',', 'how', 'are', 'you', 'doing', 'today', '?', 'This', 'is', 'an', 'example', 'sentence', 'for', 'the', 'program', '!']

(c) Compare the two sentences. Print out a list of words that occur in both sentences.

(d) Remove any punctuation from the sentence and print the sanitized sentences. It should remove at least the following characters, but it can remove more: period(“.”), comma (“,”), semicolon (“;”), and colon (“:”).

(e) Count the number of vowels in each of the sentences. Print out each vowel and the occurrences  in the each of the two sentences separately, such as:

Sentence1: a:2, e:2, i:0, etc.
Sentence2: a:1, e:2, i:2, etc.

Design a well-structured Python program to execute these tasks efficiently.

In [ ]:
#Question 3
import re

sentence1 = input("Enter first sentence: ")
sentence2 = input("Enter second sentence: ")

print("\nYou have entered:")
print("sentence1:", sentence1)
print("sentence2:", sentence2)

sentence1_list = re.findall(r'\w+|[^\w\s]', sentence1)
sentence2_list = re.findall(r'\w+|[^\w\s]', sentence2)

print(sentence1_list)
print(sentence2_list)

sentence1_words = set(sentence1_list)
sentence2_words = set(sentence2_list)

words_common = sentence1_words.intersection(sentence2_words)
print("Common words between the two sentences:", words_common)

cleaned_sentence1 = re.sub(r'[^\w\s]', '', sentence1)
print("Cleaned sentence1:", cleaned_sentence1)

cleaned_sentence2 = re.sub(r'[^\w\s]', '', sentence2)
print("Cleaned sentence2:", cleaned_sentence2)

sentence1_lower = cleaned_sentence1.lower()
sentence2_lower = cleaned_sentence2.lower()

vowels = 'aeiou'
vowel_counts_sentence1 = {v: sentence1_lower.count(v) for v in vowels}
vowel_counts_sentence2 = {v: sentence2_lower.count(v) for v in vowels}

print("Sentence1:", ', '.join([f"{v}:{vowel_counts_sentence1[v]}" for v in vowels]))
print("Sentence2:", ', '.join([f"{v}:{vowel_counts_sentence2[v]}" for v in vowels]))

count_vowels_sentence1 = sum(vowel_counts_sentence1.values())
count_vowels_sentence2 = sum(vowel_counts_sentence2.values())

print(f"Total vowels in sentence1: {count_vowels_sentence1}")
print(f"Total vowels in sentence2: {count_vowels_sentence2}")



Enter first sentence: Hello, how are you doing today?
Enter second sentence: This is an example sentence for the program!

You have entered:
sentence1: Hello, how are you doing today?
sentence2: This is an example sentence for the program!
['Hello', ',', 'how', 'are', 'you', 'doing', 'today', '?']
['This', 'is', 'an', 'example', 'sentence', 'for', 'the', 'program', '!']
Common words between the two sentences: set()
Cleaned sentence1: Hello how are you doing today
Cleaned sentence2: This is an example sentence for the program
Sentence1: a:2, e:2, i:1, o:5, u:1
Sentence2: a:3, e:6, i:2, o:2, u:0
Total vowels in sentence1: 11
Total vowels in sentence2: 13


# Question 4 (10 Points)

Design and implement a simple command-line calculator program. The program should handle both integers and floating-point numbers.

(a) Write program that takes a mathematical expression as input and evaluates it. The program should support addition, subtraction, multiplication, and division.

(b) Extend the calculator to handle parentheses in mathematical expressions. Implement the necessary logic to evaluate expressions with nested parentheses.

(c) Enhance your calculator to include additional mathematical operations such as exponentiation, square root, and modulus.

(d) Implement error handling in the calculator program. Handle cases such as division by zero and invalid input expressions. Provide meaningful error messages.

(e) Implement a command to exit the calculator.

In [ ]:
#Question 4
import re
import math
import sys
from typing import Union

def expression_evaluation(expression: str) -> Union[float, int, str]:

    try:
        expr = expression.strip().replace('^', '**')

        if len(expr) > 200:
            return "Error: Expression too long"

        if not re.match(r'^[0-9+\-*/().% sqrtabsroundlogcossin]+$', expr):
            invalid_chars = set(re.findall(r'[^0-9+\-*/().% sqrtabsroundlogcossin]', expr))
            return f"Error - Invalid characters: {', '.join(invalid_chars)}"

        allowed_functions = {'sqrt', 'abs', 'round', 'log', 'cos', 'sin'}
        words = set(re.findall(r'[a-zA-Z]+', expr))
        for word in words:
            if word not in allowed_functions:
                return f"Error - Invalid function: {word}"


        if re.search(r'(\+{2,}|/{2,}|\*{3,}|%{2,})', expr):
            return "Error - Invalid operator sequence"


        stack = []
        for char in expr:
            if char == '(':
                stack.append(char)
            elif char == ')':
                if not stack:
                    return "Error - Mismatched parentheses"
                stack.pop()
        if stack:
            return "Error - Mismatched parentheses"


        if '**' in expr:
            base, _, exponent = expr.partition('**')
            if exponent.isdigit() and int(exponent) > 1000:
                return "Error - Exponent too large to calculate"
        if re.search(r'\d{50,}', expr):
            return "Error - Number too large to calculate"


        allowed = {
            'sqrt': math.sqrt,
            'abs': abs,
            'round': round,
            'log': math.log,
            'cos': math.cos,
            'sin': math.sin,
            '__builtins__': None
        }

        output = eval(expr, allowed)

        if isinstance(output, float):
            if output.is_integer():
                return int(output)
            return round(output, 6)
        return output

    except ZeroDivisionError:
        return "Error - Division by zero not allowed"
    except ValueError as e:
        if "math domain error" in str(e):
            return "Error - Invalid math operation"
        return f"Error: {e}"
    except SyntaxError:
        return "Error - Invalid syntax"
    except TypeError:
        return "Error - Invalid operand types"
    except OverflowError:
        return "Error - Number too large to calculate"
    except Exception as e:
        return f"Error: {str(e)}"

def simple_calculator():
    print("Simple Calculator")
    print("Type 'exit' to terminate\n")

    while True:
        try:
            expression_input = input("Enter Expression: ").strip()
            if expression_input.lower() == "exit":
                print("Thank you, Bye!")
                break
            if not expression_input:
                continue

            output = expression_evaluation(expression_input)
            print(f"Output: {output}" if not isinstance(output, str) else output)

        except KeyboardInterrupt:
            print("\nOperation cancelled")
            break

if __name__ == "__main__":
    simple_calculator()

Simple Calculator
Type 'exit' to terminate

Enter Expression: 8+7
Output: 15
Enter Expression: exit
Thank you, Bye!


# Question 5 (20 points).

In the field of Data Science, data is often formatted as a comma-delimited (CSV) file, where each line in a file corresponds to a field's value. Refer to Chapter 9 (p. 106) for more information on comma-delimited files.

To answer this question, you will need to download the file [Assignment1_denton_housing.csv](https://raw.githubusercontent.com/unt-iialab/info5731-spring2022/main/assignments/Assignment1_denton_housing.csv) included with this assignment. The file contains statistics about housing in the city of Denton from 2008 to 2014. Write a program to implement the following questions.

(a) (5 pts) Calculate the difference in the number of Occupied Housing Units from year to year and print it. The difference must be calculated for the consecutive years such as 2008-2009, 2009-2010 etc. Finally, print the values in the ascending order.

(b) (5 pts) For all the years, calculate the percentage of housing units which are vacant an occupied. Print the results in the following format:

Year Vacant Housing Units Occupied Housing Units

    2008  30%   70%                          
	2009 ----- -----
	2010 ----- -----
    2011 ----- -----
	2012 ----- -----
    2013 ----- -----
	2014 ----- -----
  
  

(c) (5 pts) Calculate and print the valued and years in which the highest number of housing units were vacant and occupied. Print the results in the following format:  

                              Year	Value
	Vacant Housing Units	  -----   -----
	Occupied Housing Units	-----   -----

(d) (5 pts) Calculate the harmonic mean of the total housing units and print it out. You can find the information about harmonic mean here: https://ncalculators.com/statistics/harmonic-mean-calculator.htm

In [ ]:
#Question 5

import pandas as pd
import numpy as np

df = pd.read_csv("Assignment1_denton_housing.csv")

#a
units_occupied = df[df['title_field'] == 'Occupied Housing Units'].sort_values('year')
units_occupied['diff'] = units_occupied['value'].diff().fillna(0)
diffs = units_occupied['diff'].tolist()[1:]  # Exclude the first NaN value
sorted_diffs = sorted(diffs)
print("Differences in No. of Occupied Housing Units in Ascending Order:")
print(sorted_diffs)

#b
housing_data = df.pivot(index='year', columns='title_field', values='value')
housing_data['Vacant%'] = (housing_data['Vacant Housing Units'] / housing_data['Total Housing Units']) * 100
housing_data['Occupied%'] = (housing_data['Occupied Housing Units'] / housing_data['Total Housing Units']) * 100

print("\n Percentage of Vacant and Occupied Housing Units:")
print(housing_data[['Vacant%', 'Occupied%']].round(0).astype(int))

#c
vacant_units = df[df['title_field'] == 'Vacant Housing Units']
occupied_units = df[df['title_field'] == 'Occupied Housing Units']
max_vacant = vacant_units.loc[vacant_units['value'].idxmax()]
max_occupied = occupied_units.loc[occupied_units['value'].idxmax()]

print("\n Year and Value with Highest Vacant and Occupied Units:")
print("                          Year  Value")
print(f"Vacant Housing Units     {max_vacant['year']}   {max_vacant['value']}")
print(f"Occupied Housing Units   {max_occupied['year']}   {max_occupied['value']}")

#d
total_housing_units = df[df['title_field'] == 'Total Housing Units']['value']
harmonic_mean = len(total_housing_units) / np.sum(1 / total_housing_units)
print("\n Harmonic Mean of Total Housing Units:")
print(f"{harmonic_mean:.2f}")




Differences in No. of Occupied Housing Units in Ascending Order:
[-795.0, -303.0, 1404.0, 1565.0, 2622.0, 5091.0]

 Percentage of Vacant and Occupied Housing Units:
title_field  Vacant%  Occupied%
year                           
2008              11         89
2009               9         91
2010               8         92
2011               9         91
2012               7         93
2013               9         91
2014               6         94

 Year and Value with Highest Vacant and Occupied Units:
                          Year  Value
Vacant Housing Units     2008   4483
Occupied Housing Units   2014   46295

 Harmonic Mean of Total Housing Units:
44398.29


# **For question 6 and 7 you can take AI assitance to solve.**

Make sure you follow the instructions given in class to answer these questions.


**Important points:**

1.   You must come up with at least 10 edge cases.
2.   You should provide prompts and revised prompts given to ChatGPT.
2.   Debug your code and write comments for each block of code
3.   Analyzing error will not consider as edge case.

Edge cases are like real life scienarios which are realated to the given question.

# Question 6 (20 points).
Develop a advance Python program to manage inventory records for a prodcut managing company. The system needs functions for adding, deleting and changing products and basic search options. Your system should use CSV files to automate restocking and produce reports that show item values alongside category breakdowns. Manage edge cases and corrupted CSV files. Finally maintaine 50 products of different categories in inventory.

Prompt 1: Develop a advance Python program to manage inventory records for a prodcut managing company. The system needs functions for adding, deleting and changing products and basic search options. Your system should use CSV files to automate restocking and produce reports that show item values alongside category breakdowns. Manage edge cases and corrupted CSV files. Finally maintaine 50 products of different categories in inventory.italicized text

In [ ]:
# Here's an advanced Python inventory management system that meets your requirements:

"""
This solution includes:
CSV File Management:
Automatic file creation with headers
Data validation and corruption handling
Backup system for corrupted files
Sample data generation for initial 50 products

Core Features:
Add/Delete/Update products with validation
Flexible search functionality
Automatic restocking based on reorder levels
Detailed inventory reporting

Error Handling:
Data type validation for numeric fields
CSV structure validation
Graceful error recovery with backups
Invalid row skipping with warnings

Reporting:
Total inventory value calculation
Category-based breakdown
Product count statistics

Edge Case Handling:
Duplicate product prevention (using UUIDs)
Negative quantity prevention
Invalid data type handling
Missing file handling

To use the system:
Create an instance of InventoryManager
Use the provided methods to manage inventory
Generate reports using generate_report()
Automatic restocking happens through restock_products()

The system maintains data integrity through:
UUIDs for product identification
Regular backups
Data validation at all entry points
Automatic sample data generation
Comprehensive error handling
"""
import csv
import os
import uuid
from datetime import datetime
from collections import defaultdict

class InventoryManager:
    def __init__(self, filename='inventory.csv'):
        self.filename = filename
        self.fieldnames = ['ProductID', 'Name', 'Category', 'Price', 'Quantity', 'ReorderLevel']
        self._initialize_csv()
        self._validate_csv()
        self._generate_sample_data_if_needed()

    def _initialize_csv(self):
        if not os.path.exists(self.filename):
            with open(self.filename, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=self.fieldnames)
                writer.writeheader()

    def _validate_csv(self):
        try:
            with open(self.filename, 'r') as f:
                reader = csv.reader(f)
                headers = next(reader)
                if headers != self.fieldnames:
                    raise ValueError("Invalid CSV headers")

                for row in reader:
                    if len(row) != len(self.fieldnames):
                        raise ValueError("Invalid row length")
                    float(row[3])  # Check Price
                    int(row[4])    # Check Quantity
                    int(row[5])    # Check ReorderLevel
        except Exception as e:
            print(f"CSV validation failed: {e}, creating backup and new file")
            self._backup_csv()
            self._initialize_csv()

    def _backup_csv(self):
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        backup_name = f"{self.filename}_backup_{timestamp}.csv"
        os.rename(self.filename, backup_name)
        print(f"Created backup: {backup_name}")

    def _generate_sample_data_if_needed(self):
        products = self._read_products()
        if len(products) < 50:
            categories = ['Electronics', 'Clothing', 'Books', 'Home', 'Toys']
            for i in range(50 - len(products)):
                self.add_product(
                    name=f"Sample Product {i+1}",
                    category=categories[i % len(categories)],
                    price=round(10 + (i * 0.5), 2),
                    quantity=100,
                    reorder_level=20
                )

    def _read_products(self):
        products = []
        with open(self.filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    products.append({
                        'ProductID': row['ProductID'],
                        'Name': row['Name'],
                        'Category': row['Category'],
                        'Price': float(row['Price']),
                        'Quantity': int(row['Quantity']),
                        'ReorderLevel': int(row['ReorderLevel'])
                    })
                except:
                    print(f"Skipping invalid row: {row}")
        return products

    def _write_products(self, products):
        with open(self.filename, 'w', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=self.fieldnames)
            writer.writeheader()
            writer.writerows(products)

    def add_product(self, name, category, price, quantity, reorder_level):
        products = self._read_products()
        product_id = str(uuid.uuid4())

        products.append({
            'ProductID': product_id,
            'Name': name,
            'Category': category,
            'Price': price,
            'Quantity': quantity,
            'ReorderLevel': reorder_level
        })

        self._write_products(products)
        return product_id

    def delete_product(self, product_id):
        products = self._read_products()
        products = [p for p in products if p['ProductID'] != product_id]
        self._write_products(products)

    def update_product(self, product_id, **kwargs):
        products = self._read_products()
        for product in products:
            if product['ProductID'] == product_id:
                for key, value in kwargs.items():
                    if key in self.fieldnames and key != 'ProductID':
                        product[key] = value
                self._write_products(products)
                return True
        return False

    def search_products(self, **kwargs):
        products = self._read_products()
        results = []
        for product in products:
            match = True
            for key, value in kwargs.items():
                if key not in product or str(product[key]).lower() != str(value).lower():
                    match = False
                    break
            if match:
                results.append(product)
        return results

    def restock_products(self, restock_amount=50):
        products = self._read_products()
        updated = False
        for product in products:
            if product['Quantity'] < product['ReorderLevel']:
                product['Quantity'] += restock_amount
                updated = True
        if updated:
            self._write_products(products)
        return updated

    def generate_report(self):
        products = self._read_products()
        category_breakdown = defaultdict(lambda: {'count': 0, 'value': 0.0})
        total_inventory_value = 0.0

        for product in products:
            product_value = product['Price'] * product['Quantity']
            total_inventory_value += product_value
            category_breakdown[product['Category']]['count'] += 1
            category_breakdown[product['Category']]['value'] += product_value

        return {
            'total_value': total_inventory_value,
            'category_breakdown': dict(category_breakdown),
            'product_count': len(products)
        }

# Example usage
if __name__ == "__main__":
    manager = InventoryManager()

    # Add a new product
    new_id = manager.add_product(
        name="Wireless Mouse",
        category="Electronics",
        price=29.99,
        quantity=15,
        reorder_level=20
    )

    # Search products
    print("Search results:", manager.search_products(Category="Electronics"))

    # Update product
    manager.update_product(new_id, Quantity=10)

    # Restock products
    manager.restock_products()

    # Generate report
    report = manager.generate_report()
    print("\nInventory Report:")
    print(f"Total Inventory Value: ${report['total_value']:.2f}")
    for category, data in report['category_breakdown'].items():
        print(f"{category}: {data['count']} items, Value: ${data['value']:.2f}")

    # Delete product (example)
    # manager.delete_product(new_id)

Search results: [{'ProductID': 'e45951f6-acc4-44a8-b9ae-0902a68346a2', 'Name': 'Sample Product 1', 'Category': 'Electronics', 'Price': 10.0, 'Quantity': 100, 'ReorderLevel': 20}, {'ProductID': 'c3623aff-aeb4-424e-bb98-09b339d4b52f', 'Name': 'Sample Product 6', 'Category': 'Electronics', 'Price': 12.5, 'Quantity': 100, 'ReorderLevel': 20}, {'ProductID': '25ae5b8d-6087-499b-9ea2-3c8ff8e3efa3', 'Name': 'Sample Product 11', 'Category': 'Electronics', 'Price': 15.0, 'Quantity': 100, 'ReorderLevel': 20}, {'ProductID': '7adb5bdd-5414-4783-98f4-4a69cbce1901', 'Name': 'Sample Product 16', 'Category': 'Electronics', 'Price': 17.5, 'Quantity': 100, 'ReorderLevel': 20}, {'ProductID': '9d6701fa-f723-4243-870f-9816f9f60def', 'Name': 'Sample Product 21', 'Category': 'Electronics', 'Price': 20.0, 'Quantity': 100, 'ReorderLevel': 20}, {'ProductID': '6af0486c-6ca7-4c65-bb67-5a41bf7c083a', 'Name': 'Sample Product 26', 'Category': 'Electronics', 'Price': 22.5, 'Quantity': 100, 'ReorderLevel': 20}, {'Produ

prompt 2: these are the 10 edges cases i would like to implement Corrupted or inaccessible inventory file Unable to save inventory Adding a product with a duplicate name Attempting to delete a non-existent product Updating quantity to a negative value Updating price to zero or negative value Searching with an empty keyword Generating a report with no products Restocking with a non-existent or inaccessible file Restocking beyond maximum capacity

In [ ]:
#Here's the enhanced implementation with comprehensive handling of your 10 edge cases. Key additions are marked with comments:

"""
 Key edge case handling additions:

Corrupted File Handling

Enhanced validation in _validate_csv

Automatic backups with _backup_csv

Sample data regeneration

Write Failure Handling

Temp file writing pattern

Permission/disk full error propagation

Atomic file replacement

Duplicate Prevention

Case-insensitive name check in add_product

Custom exception raising

Delete Validation

Product existence check in delete_product

Error propagation

Quantity/Price Validation

Value checks in update_product

Negative/zero value prevention

Search Validation

Empty term detection in search_products

Clean error messaging

Empty Report Handling

Special empty state in generate_report

Clear messaging

Restock File Handling

Error wrapping in restock_products

Clean error propagation

Capacity Enforcement

MAX_CAPACITY class constant

Restocking limit checks

Comprehensive Error Handling

Custom InventoryError hierarchy

Contextual error messages

Error propagation through stack

This implementation provides:

Structured error handling with custom exceptions

Atomic file operations for data integrity

Comprehensive input validation

Clear error messaging

System state preservation

Graceful failure recovery

Each edge case is handled through a combination of preventive checks, validation routines, and structured error reporting.
"""

import csv
import os
import uuid
from datetime import datetime
from collections import defaultdict

class InventoryError(Exception):
    """Base class for inventory exceptions"""
    pass

class InventoryManager:
    MAX_CAPACITY = 1000  # For restocking limit

    def __init__(self, filename='inventory.csv'):
        self.filename = filename
        self.fieldnames = ['ProductID', 'Name', 'Category', 'Price', 'Quantity', 'ReorderLevel']
        self._initialize_csv()
        self._validate_csv()
        self._generate_sample_data_if_needed()

    # Existing initialization methods remain the same...

    def _write_products(self, products):
        """Handles write errors and disk full scenarios"""
        try:
            # Write to temporary file first
            tempfile = self.filename + '.tmp'
            with open(tempfile, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=self.fieldnames)
                writer.writeheader()
                writer.writerows(products)

            # Replace original file
            os.replace(tempfile, self.filename)

        except (PermissionError, OSError) as e:
            raise InventoryError(f"Failed to save inventory: {str(e)}") from e
        finally:
            if os.path.exists(tempfile):
                os.remove(tempfile)

    def add_product(self, name, category, price, quantity, reorder_level):
        """Handles duplicate names"""
        products = self._read_products()

        # Check for duplicate names (case-insensitive)
        if any(p['Name'].lower() == name.lower() for p in products):
            raise InventoryError(f"Product '{name}' already exists")

        # Rest of existing implementation...

    def delete_product(self, product_id):
        """Handles non-existent product deletion"""
        products = self._read_products()
        original_count = len(products)
        products = [p for p in products if p['ProductID'] != product_id]

        if len(products) == original_count:
            raise InventoryError(f"Product {product_id} not found")

        self._write_products(products)

    def update_product(self, product_id, **kwargs):
        """Handles invalid quantity/price updates"""
        valid_updates = {}
        for key, value in kwargs.items():
            if key == 'Quantity':
                if value < 0:
                    raise InventoryError("Quantity cannot be negative")
            elif key == 'Price':
                if value <= 0:
                    raise InventoryError("Price must be positive")
            valid_updates[key] = value

        # Rest of existing update logic...

    def search_products(self, **kwargs):
        """Handles empty search terms"""
        # Validate search terms
        for key, value in kwargs.items():
            if isinstance(value, str) and not value.strip():
                raise InventoryError("Empty search term provided")

        # Existing search logic...

    def restock_products(self, restock_amount=50):
        """Handles restocking limits and file issues"""
        try:
            products = self._read_products()
        except InventoryError as e:
            raise InventoryError("Cannot restock: Inventory file issues") from e

        updated = False
        for product in products:
            if product['Quantity'] < product['ReorderLevel']:
                new_quantity = product['Quantity'] + restock_amount

                # Enforce maximum capacity
                if new_quantity > self.MAX_CAPACITY:
                    new_quantity = self.MAX_CAPACITY

                if new_quantity != product['Quantity']:
                    product['Quantity'] = new_quantity
                    updated = True

        if updated:
            self._write_products(products)
        return updated

    def generate_report(self):
        """Handles empty inventory scenario"""
        products = self._read_products()

        if not products:
            return {
                'total_value': 0.0,
                'category_breakdown': {},
                'product_count': 0,
                'message': 'No products in inventory'
            }

        # Existing report logic...

# Edge Case Handling Demonstrations
if __name__ == "__main__":
    try:
        manager = InventoryManager('nonexistent.csv')

        # Test duplicate name
        try:
            manager.add_product("Sample Product 1", "Electronics", 10.99, 50, 20)
        except InventoryError as e:
            print(f"Caught error: {e}")

        # Test invalid update
        try:
            manager.update_product("invalid_id", Quantity=-5)
        except InventoryError as e:
            print(f"Caught error: {e}")

        # Test empty search
        try:
            manager.search_products(Name="")
        except InventoryError as e:
            print(f"Caught error: {e}")

        # Test restock with bad file
        bad_manager = InventoryManager('/protected/inventory.csv')
        try:
            bad_manager.restock_products()
        except InventoryError as e:
            print(f"Caught error: {e}")

    except Exception as e:
        print(f"System error: {e}")


System error: 'InventoryManager' object has no attribute '_initialize_csv'


prompt 3: System error: 'InventoryManager' object has no attribute '_initialize_csv'


[ ]


In [ ]:
#This error occurs because the _initialize_csv method is referenced in the __init__ method but wasn't defined in the final code snippet.
#Let me fix this by adding the missing initialization methods. Here's the corrected implementation:


"""
This complete implementation includes:

Full Error Handling

Custom exceptions with meaningful messages

Validation for all input parameters

Graceful recovery from file errors

Atomic file operations to prevent corruption

Edge Case Coverage

Corrupted file detection and recovery

Write failure handling (disk full, permissions)

Duplicate product prevention

Negative value validation

Empty search term detection

Restocking limits enforcement

Key Features

CSV-based storage with automatic backups

UUID-based product identification

Inventory reports with financial breakdown

Automatic restocking system

Sample data generation

Maintenance Tools

CSV validation and repair

Automatic sample data creation

Backup system for corrupted files

Capacity management for stock levels

To use the system:

Create an InventoryManager instance

Use the provided methods to manage inventory

Handle specific edge cases with try/except blocks

Generate reports using generate_report()

The code includes a self-cleaning test example that demonstrates:

Error handling for various edge cases

Restocking functionality

Report generation

Clean test file management

All 10 specified edge cases are properly handled through validation checks, error raising, and recovery mechanisms.
"""

import csv
import os
import uuid
from datetime import datetime
from collections import defaultdict

class InventoryError(Exception):
    """Base class for inventory exceptions"""
    pass

class InventoryManager:
    MAX_CAPACITY = 1000  # Maximum stock capacity

    def __init__(self, filename='inventory.csv'):
        self.filename = filename
        self.fieldnames = ['ProductID', 'Name', 'Category', 'Price', 'Quantity', 'ReorderLevel']
        self._initialize_csv()
        self._validate_csv()
        self._generate_sample_data_if_needed()

    def _initialize_csv(self):
        """Create CSV file with headers if it doesn't exist"""
        if not os.path.exists(self.filename):
            try:
                with open(self.filename, 'w', newline='') as f:
                    writer = csv.DictWriter(f, fieldnames=self.fieldnames)
                    writer.writeheader()
            except IOError as e:
                raise InventoryError(f"Failed to initialize CSV: {str(e)}") from e

    def _validate_csv(self):
        """Validate CSV structure and data integrity"""
        try:
            with open(self.filename, 'r') as f:
                reader = csv.reader(f)
                headers = next(reader)
                if headers != self.fieldnames:
                    raise ValueError("Invalid CSV headers")

                for row_num, row in enumerate(reader, start=2):
                    if len(row) != len(self.fieldnames):
                        raise ValueError(f"Invalid row {row_num}: column count mismatch")
                    try:
                        float(row[3])  # Price
                        int(row[4])    # Quantity
                        int(row[5])    # ReorderLevel
                    except ValueError:
                        raise ValueError(f"Invalid data types in row {row_num}")
        except Exception as e:
            print(f"CSV validation failed: {e}")
            self._backup_csv()
            self._initialize_csv()

    def _backup_csv(self):
        """Create timestamped backup of corrupted file"""
        try:
            timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
            backup_name = f"{self.filename}_backup_{timestamp}.csv"
            os.rename(self.filename, backup_name)
            print(f"Created backup: {backup_name}")
        except OSError as e:
            raise InventoryError(f"Backup failed: {str(e)}") from e

    def _generate_sample_data_if_needed(self):
        """Generate sample data if inventory is empty"""
        try:
            products = self._read_products()
            if len(products) < 50:
                categories = ['Electronics', 'Clothing', 'Books', 'Home', 'Toys']
                for i in range(50 - len(products)):
                    self.add_product(
                        name=f"Sample Product {i+1}",
                        category=categories[i % len(categories)],
                        price=round(10 + (i * 0.5), 2),
                        quantity=100,
                        reorder_level=20
                    )
        except InventoryError as e:
            print(f"Sample data generation failed: {str(e)}")

    def _read_products(self):
        """Read and validate products from CSV"""
        products = []
        if not os.path.exists(self.filename):
            return products

        with open(self.filename, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                try:
                    products.append({
                        'ProductID': row['ProductID'],
                        'Name': row['Name'],
                        'Category': row['Category'],
                        'Price': float(row['Price']),
                        'Quantity': int(row['Quantity']),
                        'ReorderLevel': int(row['ReorderLevel'])
                    })
                except (ValueError, KeyError):
                    print(f"Skipping invalid row: {row}")
        return products

    def _write_products(self, products):
        """Atomic write to CSV with error handling"""
        tempfile = self.filename + '.tmp'
        try:
            with open(tempfile, 'w', newline='') as f:
                writer = csv.DictWriter(f, fieldnames=self.fieldnames)
                writer.writeheader()
                writer.writerows(products)

            os.replace(tempfile, self.filename)
        except (PermissionError, OSError) as e:
            raise InventoryError(f"Failed to save inventory: {str(e)}") from e
        finally:
            if os.path.exists(tempfile):
                os.remove(tempfile)

    def add_product(self, name, category, price, quantity, reorder_level):
        """Add new product with validation"""
        products = self._read_products()

        # Check for duplicate names
        if any(p['Name'].lower() == name.lower() for p in products):
            raise InventoryError(f"Product '{name}' already exists")

        # Validate numerical values
        if price <= 0:
            raise InventoryError("Price must be positive")
        if quantity < 0:
            raise InventoryError("Quantity cannot be negative")
        if reorder_level < 0:
            raise InventoryError("Reorder level cannot be negative")

        product_id = str(uuid.uuid4())
        products.append({
            'ProductID': product_id,
            'Name': name,
            'Category': category,
            'Price': price,
            'Quantity': quantity,
            'ReorderLevel': reorder_level
        })

        self._write_products(products)
        return product_id

    def delete_product(self, product_id):
        """Delete product by ID"""
        products = self._read_products()
        original_count = len(products)
        products = [p for p in products if p['ProductID'] != product_id]

        if len(products) == original_count:
            raise InventoryError(f"Product {product_id} not found")

        self._write_products(products)

    def update_product(self, product_id, **kwargs):
        """Update product properties with validation"""
        products = self._read_products()
        found = False

        for product in products:
            if product['ProductID'] == product_id:
                found = True
                for key, value in kwargs.items():
                    if key not in self.fieldnames or key == 'ProductID':
                        raise InventoryError(f"Invalid field: {key}")

                    # Special validation for numeric fields
                    if key == 'Price':
                        if value <= 0:
                            raise InventoryError("Price must be positive")
                    elif key in ['Quantity', 'ReorderLevel']:
                        if value < 0:
                            raise InventoryError(f"{key} cannot be negative")

                    product[key] = value
                break

        if not found:
            raise InventoryError(f"Product {product_id} not found")

        self._write_products(products)
        return True

    def search_products(self, **kwargs):
        """Search products with validation"""
        # Validate search terms
        for key, value in kwargs.items():
            if key not in self.fieldnames:
                raise InventoryError(f"Invalid search field: {key}")
            if isinstance(value, str) and not value.strip():
                raise InventoryError("Empty search term provided")

        products = self._read_products()
        results = []

        for product in products:
            match = True
            for key, value in kwargs.items():
                if key not in product:
                    match = False
                    break
                if str(product[key]).lower() != str(value).lower():
                    match = False
                    break
            if match:
                results.append(product)

        return results

    def restock_products(self, restock_amount=50):
        """Restock products below reorder level"""
        try:
            products = self._read_products()
        except InventoryError as e:
            raise InventoryError("Cannot restock: Inventory file issues") from e

        updated = False
        for product in products:
            if product['Quantity'] < product['ReorderLevel']:
                new_quantity = product['Quantity'] + restock_amount

                # Enforce maximum capacity
                if new_quantity > self.MAX_CAPACITY:
                    new_quantity = self.MAX_CAPACITY

                if new_quantity != product['Quantity']:
                    product['Quantity'] = new_quantity
                    updated = True

        if updated:
            self._write_products(products)
        return updated

    def generate_report(self):
        """Generate inventory report"""
        products = self._read_products()
        category_breakdown = defaultdict(lambda: {'count': 0, 'value': 0.0})
        total_inventory_value = 0.0

        for product in products:
            product_value = product['Price'] * product['Quantity']
            total_inventory_value += product_value
            category_breakdown[product['Category']]['count'] += 1
            category_breakdown[product['Category']]['value'] += product_value

        report = {
            'total_value': total_inventory_value,
            'category_breakdown': dict(category_breakdown),
            'product_count': len(products)
        }

        if not products:
            report['message'] = 'No products in inventory'

        return report


# Example usage with edge case testing
if __name__ == "__main__":
    try:
        # Initialize with test file
        manager = InventoryManager('test_inventory.csv')

        # Test adding duplicate product
        try:
            manager.add_product("Sample Product 1", "Electronics", 10.99, 50, 20)
        except InventoryError as e:
            print(f"Duplicate add prevented: {e}")

        # Test invalid update
        test_id = list(manager.search_products(Name="Sample Product 1"))[0]['ProductID']
        try:
            manager.update_product(test_id, Quantity=-5)
        except InventoryError as e:
            print(f"Invalid update prevented: {e}")

        # Test empty search
        try:
            manager.search_products(Name="")
        except InventoryError as e:
            print(f"Empty search prevented: {e}")

        # Test restocking
        print("\nBefore restock:")
        print([p['Quantity'] for p in manager.search_products(Category="Electronics")][:3])
        manager.restock_products()
        print("After restock:")
        print([p['Quantity'] for p in manager.search_products(Category="Electronics")][:3])

        # Generate report
        report = manager.generate_report()
        print("\nInventory Report:")
        print(f"Total Value: ${report['total_value']:.2f}")
        print(f"Product Count: {report['product_count']}")
        for category, data in report['category_breakdown'].items():
            print(f"{category}: {data['count']} items, Value: ${data['value']:.2f}")

    except Exception as e:
        print(f"System error: {e}")
    finally:
        # Cleanup test file
        if os.path.exists('test_inventory.csv'):
            os.remove('test_inventory.csv')


Duplicate add prevented: Product 'Sample Product 1' already exists
Invalid update prevented: Quantity cannot be negative
Empty search prevented: Empty search term provided

Before restock:
[100, 100, 100]
After restock:
[100, 100, 100]

Inventory Report:
Total Value: $111250.00
Product Count: 50
Electronics: 10 items, Value: $21250.00
Clothing: 10 items, Value: $21750.00
Books: 10 items, Value: $22250.00
Home: 10 items, Value: $22750.00
Toys: 10 items, Value: $23250.00


Prompt 4: Analyze the final output

Duplicate add prevented: Product 'Sample Product 1' already exists Invalid update prevented: Quantity cannot be negative Empty search prevented: Empty search term provided

Before restock: [100, 100, 100] After restock: [100, 100, 100]

Inventory Report: Total Value:  111250.00ProductCount:50Electronics:10items,Value: 21250.00 Clothing: 10 items, Value:  21750.00Books:10items,Value: 22250.00 Home: 10 items, Value:  22750.00Toys:10items,Value: 23250.00

The output demonstrates the system is working correctly based on the test parameters. Let's analyze why the restocking didn't change quantities and explain the behavior:

Why Quantities Didn't Change:

Sample Data Configuration:

Sample products are created with:
quantity=100 reorder_level=20 Since 100 > 20, these products don't need restocking

Restock Logic:

if product['Quantity'] < product['ReorderLevel']:

# Only restock when current quantity < reorder level
All products were already above their reorder threshold

To Test Restocking Properly, modify the test case to include products below their reorder level:

Add a product that NEEDS restocking
low_stock_id = manager.add_product( name="Emergency Flashlight", category="Electronics", price=14.99, quantity=15, # Below reorder level reorder_level=20 )

print("\nBefore restock:", manager.search_products(Name="Emergency Flashlight")[0]['Quantity']) manager.restock_products() print("After restock:", manager.search_products(Name="Emergency Flashlight")[0]['Quantity'])

Expected Output: Before restock: 15 After restock: 65 # 15 + 50 restock Key System Characteristics Verified:

Duplicate Prevention Cannot add "Sample Product 1" twice

Negative Value Protection Blocks Quantity=-5 update

Input Validation Rejects empty search terms

Report Accuracy Correctly calculates:

Total value: 111

manager.add_product("Bulk Item", "Home", 9.99, 980, 100) manager.restock_products(restock_amount=100)

Quantity should cap at 1000
Balanced category distribution (10 items each)

To Test Restocking Scenarios: Create products below reorder level Test restocking with custom amounts Verify MAX_CAPACITY enforcement:

manager.add_product("Bulk Item", "Home", 9.99, 980, 100) manager.restock_products(restock_amount=100)

Quantity should cap at 1000
This output confirms the system is:

Preventing invalid operations ✅ Maintaining data integrity ✅ Generating accurate reports ✅ Only restocking when needed ✅

The unchanged quantities are correct behavior given the test data parameters - not a system error.

# Question 7 (20 points)

Create a well desined Python program for a flight booking system. Offer core functions for adding new flights, finding trips, reserving and releasing seating space and creating performance reports. Ensure the system manages edge cases like invalid input, overbooking, and cancellations. Finally, extend the booking system by including advanced features and maintain about 50 flight in the system.

prompt 1: Create a well desined Python program for a flight booking system. Offer core functions for adding new flights, finding trips, reserving and releasing seating space and creating performance reports. Ensure the system manages edge cases like invalid input, overbooking, and cancellations. Finally, extend the booking system by including advanced features and maintain about 50 flight in the system.

In [ ]:
#Here's the complete code for the flight booking system in one snippet:
"""
This code includes the necessary classes and methods for the flight booking system, as well as the creation of 50 example flights.
Feel free to extend it further or customize it to your needs! If you have any more questions or need additional features, just let me know.
"""
import random

class Flight:
    def __init__(self, flight_number, origin, destination, total_seats):
        self.flight_number = flight_number
        self.origin = origin
        self.destination = destination
        self.total_seats = total_seats
        self.available_seats = total_seats
        self.reserved_seats = 0

class FlightBookingSystem:
    def __init__(self):
        self.flights = {}

    def add_flight(self, flight_number, origin, destination, total_seats):
        if not flight_number or not origin or not destination or total_seats <= 0:
            print("Invalid flight details provided.")
            return
        if flight_number in self.flights:
            print(f"Flight {flight_number} already exists.")
        else:
            flight = Flight(flight_number, origin, destination, total_seats)
            self.flights[flight_number] = flight
            print(f"Flight {flight_number} added successfully.")

    def find_trip(self, origin, destination):
        trips = [flight for flight in self.flights.values() if flight.origin == origin and flight.destination == destination]
        if trips:
            for flight in trips:
                print(f"Flight {flight.flight_number} from {flight.origin} to {flight.destination}, available seats: {flight.available_seats}")
        else:
            print(f"No flights found from {origin} to {destination}.")

    def reserve_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.available_seats > 0:
                flight.available_seats -= 1
                flight.reserved_seats += 1
                print(f"Seat reserved on flight {flight_number}.")
            else:
                print(f"Flight {flight_number} is fully booked.")
        else:
            print(f"Flight {flight_number} not found.")

    def release_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Seat released on flight {flight_number}.")
            else:
                print(f"No reserved seats to release on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def cancel_reservation(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Reservation cancelled on flight {flight_number}.")
            else:
                print(f"No reservations to cancel on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def performance_report(self):
        for flight_number, flight in self.flights.items():
            print(f"Flight {flight_number}: Total seats: {flight.total_seats}, Reserved seats: {flight.reserved_seats}, Available seats: {flight.available_seats}")

booking_system = FlightBookingSystem()

# Adding 50 example flights
for i in range(1, 51):
    flight_number = f"FL{i:03d}"
    origin = f"City{random.randint(1, 10)}"
    destination = f"City{random.randint(11, 20)}"
    total_seats = random.randint(50, 200)
    booking_system.add_flight(flight_number, origin, destination, total_seats)

# Performance report to verify flights
booking_system.performance_report()



Flight FL001 added successfully.
Flight FL002 added successfully.
Flight FL003 added successfully.
Flight FL004 added successfully.
Flight FL005 added successfully.
Flight FL006 added successfully.
Flight FL007 added successfully.
Flight FL008 added successfully.
Flight FL009 added successfully.
Flight FL010 added successfully.
Flight FL011 added successfully.
Flight FL012 added successfully.
Flight FL013 added successfully.
Flight FL014 added successfully.
Flight FL015 added successfully.
Flight FL016 added successfully.
Flight FL017 added successfully.
Flight FL018 added successfully.
Flight FL019 added successfully.
Flight FL020 added successfully.
Flight FL021 added successfully.
Flight FL022 added successfully.
Flight FL023 added successfully.
Flight FL024 added successfully.
Flight FL025 added successfully.
Flight FL026 added successfully.
Flight FL027 added successfully.
Flight FL028 added successfully.
Flight FL029 added successfully.
Flight FL030 added successfully.
Flight FL0

prompt 2:no seats were reserved or booked and add more reserved or book more seats in every flight



In [1]:
#Let's reserve more seats on every flight that includes seat reservation, seat release and cancellation features. Here's the updated code snippet that reserves some seats on each flight:
import random

class Flight:
    def __init__(self, flight_number, origin, destination, total_seats):
        self.flight_number = flight_number
        self.origin = origin
        self.destination = destination
        self.total_seats = total_seats
        self.available_seats = total_seats
        self.reserved_seats = 0

class FlightBookingSystem:
    def __init__(self):
        self.flights = {}

    def add_flight(self, flight_number, origin, destination, total_seats):
        if not flight_number or not origin or not destination or total_seats <= 0:
            print("Invalid flight details provided.")
            return
        if flight_number in self.flights:
            print(f"Flight {flight_number} already exists.")
        else:
            flight = Flight(flight_number, origin, destination, total_seats)
            self.flights[flight_number] = flight
            print(f"Flight {flight_number} added successfully.")

    def find_trip(self, origin, destination):
        trips = [flight for flight in self.flights.values() if flight.origin == origin and flight.destination == destination]
        if trips:
            for flight in trips:
                print(f"Flight {flight.flight_number} from {flight.origin} to {flight.destination}, available seats: {flight.available_seats}")
        else:
            print(f"No flights found from {origin} to {destination}.")

    def reserve_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.available_seats > 0:
                flight.available_seats -= 1
                flight.reserved_seats += 1
                print(f"Seat reserved on flight {flight_number}.")
            else:
                print(f"Flight {flight_number} is fully booked.")
        else:
            print(f"Flight {flight_number} not found.")

    def release_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Seat released on flight {flight_number}.")
            else:
                print(f"No reserved seats to release on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def cancel_reservation(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Reservation cancelled on flight {flight_number}.")
            else:
                print(f"No reservations to cancel on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def performance_report(self):
        for flight_number, flight in self.flights.items():
            print(f"Flight {flight_number}: Total seats: {flight.total_seats}, Reserved seats: {flight.reserved_seats}, Available seats: {flight.available_seats}")

booking_system = FlightBookingSystem()

# Adding 50 example flights
for i in range(1, 51):
    flight_number = f"FL{i:03d}"
    origin = f"City{random.randint(1, 10)}"
    destination = f"City{random.randint(11, 20)}"
    total_seats = random.randint(50, 200)
    booking_system.add_flight(flight_number, origin, destination, total_seats)

# Reserve more seats on each flight
for flight in booking_system.flights.values():
    # Reserve a random number of seats between 1 and half of the total seats
    seats_to_reserve = random.randint(1, flight.total_seats // 2)
    for _ in range(seats_to_reserve):
        booking_system.reserve_seat(flight.flight_number)

# Generate performance report
booking_system.performance_report()



Flight FL001 added successfully.
Flight FL002 added successfully.
Flight FL003 added successfully.
Flight FL004 added successfully.
Flight FL005 added successfully.
Flight FL006 added successfully.
Flight FL007 added successfully.
Flight FL008 added successfully.
Flight FL009 added successfully.
Flight FL010 added successfully.
Flight FL011 added successfully.
Flight FL012 added successfully.
Flight FL013 added successfully.
Flight FL014 added successfully.
Flight FL015 added successfully.
Flight FL016 added successfully.
Flight FL017 added successfully.
Flight FL018 added successfully.
Flight FL019 added successfully.
Flight FL020 added successfully.
Flight FL021 added successfully.
Flight FL022 added successfully.
Flight FL023 added successfully.
Flight FL024 added successfully.
Flight FL025 added successfully.
Flight FL026 added successfully.
Flight FL027 added successfully.
Flight FL028 added successfully.
Flight FL029 added successfully.
Flight FL030 added successfully.
Flight FL0

Prompt 3: try to add 10 edge cases and add print statement so that it can be understood easily.



In [ ]:
"""
Absolutely! I'll add print statements for all the edge cases to make it clear whether each case is handled properly. Here's the updated code:
I've added print statements for all the edge cases to make it clear when each case is being tested and whether the flight booking system handles it properly.
Let me know if you have any questions or need further assistance! 😊✈️
"""

import random

class Flight:
    def __init__(self, flight_number, origin, destination, total_seats):
        self.flight_number = flight_number
        self.origin = origin
        self.destination = destination
        self.total_seats = total_seats
        self.available_seats = total_seats
        self.reserved_seats = 0

class FlightBookingSystem:
    def __init__(self):
        self.flights = {}

    def add_flight(self, flight_number, origin, destination, total_seats):
        if not flight_number or not origin or not destination or total_seats <= 0:
            print(f"Invalid flight details provided: {flight_number}, {origin}, {destination}, {total_seats}")
            return
        if flight_number in self.flights:
            print(f"Flight {flight_number} already exists.")
        else:
            flight = Flight(flight_number, origin, destination, total_seats)
            self.flights[flight_number] = flight
            print(f"Flight {flight_number} added successfully.")

    def find_trip(self, origin, destination):
        trips = [flight for flight in self.flights.values() if flight.origin == origin and flight.destination == destination]
        if trips:
            for flight in trips:
                print(f"Flight {flight.flight_number} from {flight.origin} to {flight.destination}, available seats: {flight.available_seats}")
        else:
            print(f"No flights found from {origin} to {destination}.")

    def reserve_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.available_seats > 0:
                flight.available_seats -= 1
                flight.reserved_seats += 1
                print(f"Seat reserved on flight {flight_number}.")
            else:
                print(f"Flight {flight_number} is fully booked.")
        else:
            print(f"Flight {flight_number} not found.")

    def release_seat(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Seat released on flight {flight_number}.")
            else:
                print(f"No reserved seats to release on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def cancel_reservation(self, flight_number):
        if flight_number in self.flights:
            flight = self.flights[flight_number]
            if flight.reserved_seats > 0:
                flight.reserved_seats -= 1
                flight.available_seats += 1
                print(f"Reservation cancelled on flight {flight_number}.")
            else:
                print(f"No reservations to cancel on flight {flight_number}.")
        else:
            print(f"Flight {flight_number} not found.")

    def performance_report(self):
        for flight_number, flight in self.flights.items():
            print(f"Flight {flight_number}: Total seats: {flight.total_seats}, Reserved seats: {flight.reserved_seats}, Available seats: {flight.available_seats}")

booking_system = FlightBookingSystem()

# Adding 50 example flights
for i in range(1, 51):
    flight_number = f"FL{i:03d}"
    origin = f"City{random.randint(1, 10)}"
    destination = f"City{random.randint(11, 20)}"
    total_seats = random.randint(50, 200)
    booking_system.add_flight(flight_number, origin, destination, total_seats)

# Reserve more seats on each flight
for flight in booking_system.flights.values():
    # Reserve a random number of seats between 1 and half of the total seats
    seats_to_reserve = random.randint(1, flight.total_seats // 2)
    for _ in range(seats_to_reserve):
        booking_system.reserve_seat(flight.flight_number)

# Generating edge cases
print("\n### Edge Cases ###")

# 1. Adding a flight with invalid details
print("\n1. Adding a flight with invalid details")
booking_system.add_flight("", "City1", "City2", 100)
booking_system.add_flight("FL051", "", "City2", 100)
booking_system.add_flight("FL052", "City1", "", 100)
booking_system.add_flight("FL053", "City1", "City2", 0)

# 2. Adding a flight that already exists
print("\n2. Adding a flight that already exists")
booking_system.add_flight("FL001", "City1", "City2", 100)

# 3. Reserving a seat on a non-existing flight
print("\n3. Reserving a seat on a non-existing flight")
booking_system.reserve_seat("FL999")

# 4. Releasing a seat on a non-existing flight
print("\n4. Releasing a seat on a non-existing flight")
booking_system.release_seat("FL999")

# 5. Cancelling a reservation on a non-existing flight
print("\n5. Cancelling a reservation on a non-existing flight")
booking_system.cancel_reservation("FL999")

# 6. Overbooking a flight (trying to reserve more seats than available)
print("\n6. Overbooking a flight")
flight_number = "FL001"
for _ in range(booking_system.flights[flight_number].total_seats + 1):
    booking_system.reserve_seat(flight_number)

# 7. Releasing more seats than reserved
print("\n7. Releasing more seats than reserved")
flight_number = "FL002"
booking_system.release_seat(flight_number)
booking_system.release_seat(flight_number)

# 8. Cancelling more reservations than reserved
print("\n8. Cancelling more reservations than reserved")
flight_number = "FL003"
booking_system.cancel_reservation(flight_number)
booking_system.cancel_reservation(flight_number)

# 9. Finding trips with invalid origin and destination
print("\n9. Finding trips with invalid origin and destination")
booking_system.find_trip("", "City2")
booking_system.find_trip("City1", "")

# 10. Finding trips where no flights exist
print("\n10. Finding trips where no flights exist")
booking_system.find_trip("City1", "City100")

# Generate performance report
print("\n### Performance Report ###")
booking_system.performance_report()


Flight FL001 added successfully.
Flight FL002 added successfully.
Flight FL003 added successfully.
Flight FL004 added successfully.
Flight FL005 added successfully.
Flight FL006 added successfully.
Flight FL007 added successfully.
Flight FL008 added successfully.
Flight FL009 added successfully.
Flight FL010 added successfully.
Flight FL011 added successfully.
Flight FL012 added successfully.
Flight FL013 added successfully.
Flight FL014 added successfully.
Flight FL015 added successfully.
Flight FL016 added successfully.
Flight FL017 added successfully.
Flight FL018 added successfully.
Flight FL019 added successfully.
Flight FL020 added successfully.
Flight FL021 added successfully.
Flight FL022 added successfully.
Flight FL023 added successfully.
Flight FL024 added successfully.
Flight FL025 added successfully.
Flight FL026 added successfully.
Flight FL027 added successfully.
Flight FL028 added successfully.
Flight FL029 added successfully.
Flight FL030 added successfully.
Flight FL0

prompt 4:Hey Copilot, can you help improve my flight booking system to handle edge cases better?

In [ ]:
"""
Added input validation for flight/passenger details, case normalization to prevent duplicates (e.g., FL200 ≠ fl200), overbooking prevention, and enhanced error logging.
Introduced passenger tracking, atomic seat management, and utilization metrics in performance reports.
"""

import json
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    force=True
)

class Passenger:
    def __init__(self, name, contact):
        if not name.strip() or not contact.strip():
            raise ValueError("Name/contact cannot be empty")
        self.name = name.strip().title()
        self.contact = contact.strip()

class Flight:
    def __init__(self, flight_number, origin, destination, total_seats):
        if total_seats <= 0:
            raise ValueError("Total seats must be > 0")

        self.flight_number = flight_number.strip().upper()
        self.origin = origin.strip().title()
        self.destination = destination.strip().title()
        self.total_seats = total_seats
        self.available_seats = total_seats
        self.reserved_seats = 0
        self.passengers = {}

    def to_dict(self):
        return {
            "flight_number": self.flight_number,
            "origin": self.origin,
            "destination": self.destination,
            "total_seats": self.total_seats,
            "available_seats": self.available_seats,
            "reserved_seats": self.reserved_seats,
            "passengers": {pid: p.__dict__ for pid, p in self.passengers.items()},
        }

    @classmethod
    def from_dict(cls, data):
        try:
            if data["total_seats"] <= 0:
                raise ValueError("Invalid seat count in saved data")
            return cls(
                data["flight_number"],
                data["origin"],
                data["destination"],
                data["total_seats"]
            )
        except KeyError as e:
            raise ValueError(f"Missing field: {str(e)}")

class FlightBookingSystem:
    def __init__(self):
        self.flights = {}
        self.load_flights()

    def load_flights(self):
        try:
            with open("flights.json", "r") as f:
                data = json.load(f)
                self.flights = {}
                for fid, fdata in data.items():
                    try:
                        flight = Flight.from_dict(fdata)
                        flight.available_seats = fdata["available_seats"]
                        flight.reserved_seats = fdata["reserved_seats"]
                        flight.passengers = {
                            pid: Passenger(p["name"], p["contact"])
                            for pid, p in fdata["passengers"].items()
                        }
                        self.flights[fid] = flight
                    except ValueError as e:
                        logging.error(f"Skipping invalid flight {fid}: {str(e)}")
        except (FileNotFoundError, json.JSONDecodeError):
            self.flights = {}

    def save_flights(self):
        with open("flights.json", "w") as f:
            json.dump(
                {fid: flight.to_dict() for fid, flight in self.flights.items()},
                f,
                indent=2
            )

    def add_flight(self, flight_number, origin, destination, total_seats):
        try:
            flight_number = flight_number.strip().upper()
            origin = origin.strip().title()
            destination = destination.strip().title()

            if not flight_number:
                raise ValueError("Flight number cannot be empty")
            if not origin or not destination:
                raise ValueError("Origin/destination cannot be empty")
            if total_seats <= 0:
                raise ValueError("Total seats must be > 0")
            if flight_number in self.flights:
                raise ValueError("Flight already exists")

            self.flights[flight_number] = Flight(
                flight_number, origin, destination, total_seats
            )
            logging.info(f"Added flight {flight_number}")
            self.save_flights()
        except ValueError as e:
            logging.error(f"Add flight failed: {str(e)}")

    def find_trip(self, origin, destination):
        try:
            origin = origin.strip().title()
            destination = destination.strip().title()

            if not origin or not destination:
                raise ValueError("Invalid search parameters")

            results = [
                flight for flight in self.flights.values()
                if flight.origin == origin
                and flight.destination == destination
            ]

            if not results:
                logging.info(f"No flights from {origin} to {destination}")
                return

            for flight in results:
                logging.info(
                    f"Flight {flight.flight_number}: "
                    f"{flight.origin} → {flight.destination} | "
                    f"Seats: {flight.available_seats}/{flight.total_seats}"
                )
        except Exception as e:
            logging.error(f"Search error: {str(e)}")

    def reserve_seat(self, flight_number, passenger_name, passenger_contact):
        try:
            flight_number = flight_number.strip().upper()
            passenger_name = passenger_name.strip().title()

            if flight_number not in self.flights:
                raise ValueError("Flight not found")

            flight = self.flights[flight_number]

            if flight.available_seats <= 0:
                raise ValueError("Flight full")

            passenger_id = f"{passenger_name.lower()}_{flight_number}"
            if passenger_id in flight.passengers:
                raise ValueError("Passenger already booked")

            flight.passengers[passenger_id] = Passenger(passenger_name, passenger_contact)
            flight.available_seats -= 1
            flight.reserved_seats += 1
            logging.info(f"Booked {passenger_name} on {flight_number}")
            self.save_flights()
        except ValueError as e:
            logging.error(f"Booking failed: {str(e)}")

    def release_seat(self, flight_number, passenger_name):
        try:
            flight_number = flight_number.strip().upper()
            passenger_name = passenger_name.strip().title()

            if flight_number not in self.flights:
                raise ValueError("Flight not found")

            flight = self.flights[flight_number]
            passenger_id = f"{passenger_name.lower()}_{flight_number}"

            if passenger_id not in flight.passengers:
                raise ValueError("No booking found")

            del flight.passengers[passenger_id]
            flight.available_seats += 1
            flight.reserved_seats -= 1
            logging.info(f"Released seat for {passenger_name}")
            self.save_flights()
        except ValueError as e:
            logging.error(f"Release failed: {str(e)}")

    def cancel_reservation(self, flight_number, passenger_name):
        self.release_seat(flight_number, passenger_name)

    def performance_report(self):
        if not self.flights:
            logging.info("No flights available")
            return

        logging.info("\n=== PERFORMANCE REPORT ===")
        for flight in self.flights.values():
            utilization = (flight.reserved_seats / flight.total_seats) * 100
            logging.info(
                f"Flight {flight.flight_number}:\n"
                f"Route: {flight.origin} → {flight.destination}\n"
                f"Capacity: {flight.total_seats} | "
                f"Booked: {flight.reserved_seats} | "
                f"Available: {flight.available_seats}\n"
                f"Utilization: {utilization:.1f}%\n"
            )

if __name__ == "__main__":
    # Clear previous data for clean testing
    open("flights.json", "w").close()

    system = FlightBookingSystem()

    print("\n=== Testing 10 Edge Cases ===")

    # 1. Add invalid flights
    print("\n1. Invalid flight additions:")
    system.add_flight("", "NY", "London", 100)     # Empty flight number
    system.add_flight("FL101", "", "Paris", 200)   # Empty origin
    system.add_flight("FL102", "Tokyo", "", 300)   # Empty destination
    system.add_flight("FL103", "Berlin", "Rome", 0)# Invalid seats

    # 2. Duplicate flight
    print("\n2. Duplicate flight:")
    system.add_flight("FL200", "Mumbai", "Delhi", 150)
    system.add_flight("fl200", "Mumbai", "Delhi", 200)  # Case duplicate

    # 3. Reserve on non-existent flight
    print("\n3. Reserve invalid flight:")
    system.reserve_seat("FL999", "Alice", "alice@test.com")

    # 4. Release on non-existent flight
    print("\n4. Release invalid flight:")
    system.release_seat("FL999", "Bob")

    # 5. Cancel on non-existent flight
    print("\n5. Cancel invalid flight:")
    system.cancel_reservation("FL999", "Charlie")

    # 6. Overbooking test
    print("\n6. Overbooking test:")
    system.add_flight("FL300", "London", "Dubai", 2)
    system.reserve_seat("FL300", "Dave", "dave@test.com")
    system.reserve_seat("FL300", "Eve", "eve@test.com")
    system.reserve_seat("FL300", "Frank", "frank@test.com")  # Should fail

    # 7. Release non-existent booking
    print("\n7. Release invalid booking:")
    system.release_seat("FL300", "Grace")

    # 8. Cancel non-existent booking
    print("\n8. Cancel invalid booking:")
    system.cancel_reservation("FL300", "Henry")

    # 9. Invalid search
    print("\n9. Invalid search:")
    system.find_trip("", "Dubai")
    system.find_trip("London", "")

    # 10. Non-existent route
    print("\n10. Non-existent route:")
    system.find_trip("Sydney", "Tokyo")

    # Valid operations demo
    print("\n=== Valid Operations Demo ===")
    system.add_flight("FL400", "Paris", "Rome", 3)
    system.reserve_seat("FL400", "Ivy", "ivy@test.com")
    system.reserve_seat("FL400", "Jack", "jack@test.com")
    system.release_seat("FL400", "Ivy")
    system.find_trip("Paris", "Rome")

    print("\n=== Final Report ===")
    system.performance_report()

2025-02-04 05:32:43,860 - ERROR - Add flight failed: Flight number cannot be empty
2025-02-04 05:32:43,861 - ERROR - Add flight failed: Origin/destination cannot be empty
2025-02-04 05:32:43,865 - ERROR - Add flight failed: Origin/destination cannot be empty
2025-02-04 05:32:43,868 - ERROR - Add flight failed: Total seats must be > 0
2025-02-04 05:32:43,870 - INFO - Added flight FL200
2025-02-04 05:32:43,874 - ERROR - Add flight failed: Flight already exists
2025-02-04 05:32:43,876 - ERROR - Booking failed: Flight not found
2025-02-04 05:32:43,878 - ERROR - Release failed: Flight not found
2025-02-04 05:32:43,879 - ERROR - Release failed: Flight not found
2025-02-04 05:32:43,880 - INFO - Added flight FL300
2025-02-04 05:32:43,882 - INFO - Booked Dave on FL300
2025-02-04 05:32:43,884 - INFO - Booked Eve on FL300
2025-02-04 05:32:43,886 - ERROR - Booking failed: Flight full
2025-02-04 05:32:43,888 - ERROR - Release failed: No booking found
2025-02-04 05:32:43,889 - ERROR - Release failed


=== Testing 10 Edge Cases ===

1. Invalid flight additions:

2. Duplicate flight:

3. Reserve invalid flight:

4. Release invalid flight:

5. Cancel invalid flight:

6. Overbooking test:

7. Release invalid booking:

8. Cancel invalid booking:

9. Invalid search:

10. Non-existent route:

=== Valid Operations Demo ===

=== Final Report ===


# Mandatory Question

Provide your thoughts on the assignment. What did you find challenging, and what aspects did you enjoy? Your opinion on the provided time to complete the assignment. Share any suggestions for improvement. Your feedback will be valuable for enhancing the learning experience.

In [ ]:
I really liked doing this assignment. I felt question 6 and 7 as more challenging. Time provided for this assignemnt is fine. Thanks for the assignment.